"""baseline_schema

Revision ID: 351c9f30665d
Revises: 
Create Date: 2026-05-27 15:55:47.793303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351c9f30665d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fen_eval_cache',
    sa.Column('fen_hash', sa.String(length=64), nullable=False),
    sa.Column('eval_cp', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('fen_hash')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('chesscom_username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('batch_analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('games_analyzed', sa.Integer(), nullable=True),
    sa.Column('portfolio_data', sa.JSON(), nullable=True),
    sa.Column('accuracy_trend', sa.JSON(), nullable=True),
    sa.Column('opening_stats', sa.JSON(), nullable=True),
    sa.Column('tactical_summary', sa.JSON(), nullable=True),
    sa.Column('claude_insights', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.Column('white_player', sa.String(), nullable=True),
    sa.Column('black_player', sa.String(), nullable=True),
    sa.Column('white_elo', sa.Integer(), nullable=True),
    sa.Column('black_elo', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('time_control', sa.String(), nullable=True),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('opening', sa.String(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='uq_game_user_source_external')
    )
    op.create_table('import_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('games_imported', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rating_history', sa.JSON(), nullable=True),
    sa.Column('accuracy_history', sa.JSON(), nullable=True),
    sa.Column('phase_accuracy', sa.JSON(), nullable=True),
    sa.Column('time_pressure', sa.JSON(), nullable=True),
    sa.Column('openings_white', sa.JSON(), nullable=True),
    sa.Column('openings_black', sa.JSON(), nullable=True),
    sa.Column('opponent_openings', sa.JSON(), nullable=True),
    sa.Column('claude_profile', sa.JSON(), nullable=True),
    sa.Column('win_pct_white', sa.Float(), nullable=True),
    sa.Column('win_pct_black', sa.Float(), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('total_wins', sa.Integer(), nullable=True),
    sa.Column('total_draws', sa.Integer(), nullable=True),
    sa.Column('total_losses', sa.Integer(), nullable=True),
    sa.Column('claude_error', sa.Text(), nullable=True),
    sa.Column('games_total', sa.Integer(), nullable=True),
    sa.Column('games_done', sa.Integer(), nullable=True),
    sa.Column('progress', sa.String(), nullable=True),
    sa.Column('game_count_at_last_build', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('game_analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('accuracy_white', sa.Float(), nullable=True),
    sa.Column('accuracy_black', sa.Float(), nullable=True),
    sa.Column('brilliants_white', sa.Integer(), nullable=True),
    sa.Column('brilliants_black', sa.Integer(), nullable=True),
    sa.Column('blunders_white', sa.Integer(), nullable=True),
    sa.Column('blunders_black', sa.Integer(), nullable=True),
    sa.Column('mistakes_white', sa.Integer(), nullable=True),
    sa.Column('mistakes_black', sa.Integer(), nullable=True),
    sa.Column('inaccuracies_white', sa.Integer(), nullable=True),
    sa.Column('inaccuracies_black', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('claude_summary', sa.Text(), nullable=True),
    sa.Column('key_moments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('moves',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('san', sa.String(), nullable=False),
    sa.Column('uci', sa.String(), nullable=False),
    sa.Column('fen_after', sa.String(), nullable=False),
    sa.Column('eval_before', sa.Float(), nullable=True),
    sa.Column('eval_after', sa.Float(), nullable=True),
    sa.Column('best_move', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    op.drop_table('game_analyses')
    op.drop_table('player_profiles')
    op.drop_table('import_jobs')
    op.drop_table('games')
    op.drop_table('batch_analyses')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('fen_eval_cache')
    # ### end Alembic commands ###
